### ISSUE TITLE
When stopping and then starting the BPMs are not set to the starting point

### ISSUE THREAD

**Issue by LittleHaku** [raghavio/accelonome#10]
What the title says, imagine I'm going from 100 to 150 BPM increasing by 5 and I fck up at 135 and want to restart again so I can practice slowly, I click the "timer" with the BPMs to stop it, then press start again and goes back to 135, there should be to start from 0, that is your decision but I would make default to go back to the start if it is stopped by pressing the "timer" and then another button down with the pause ( || ) icon and then when it pauses and you press start continues with the BPM it was on.
Hope I explained myself,

**Comment by raghavio** [comment]
Hi. Thanks for writing this. Really appreciate it.
I'm aware of this. I earlier had a reset button which I removed thinking just a start/stop should be sufficient. I did contemplate on this and thought that if someone stops it they might want to resume it where they stopped. Let me mull over this. I'll either do what you asked or add a separate reset button to achieve the same. For now, you can simple re-edit the starting tempo field and it will pick whatever value you enter.

**Comment by raghavio** [comment]
I've added a reset option.
